spring:
  application:
    name: mpc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/mcp
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 20
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 15000
      register-mbeans: true
      connection-test-query: select 1 from dual
      leak-detection-threshold: 30000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mcp:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: admin
    password: ${REDIS_PASSWORD}
  mongo:
    jks:
      path:
      password:
    host: ${MONGODB_HOST}
    port: ${MONGODB_PORT}
    username: admin
    password: ${MONGODB_PASSWORD}
    authentication-database: admin
ricciliao:
  x:
    common:
      consumer: mcp
      springdoc:
        title: MCP
        description: Multi-Cache Provider
        summary: ðŸŽ– Inspiration
        enable: true
      crypto-password: ${CRYPTO_PWD}
    log:
      executor:
        enable: true
logging:
  level:
    com:
      mongodb: DEBUG