spring:
  application:
    version: @project.version@
    name: cache-provider
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cache-provider:
  redis:
    consumer-list:
      - consumer: message
        store-list:
          - store: code
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            database: 1
            addition:
              max-idle: 20
              max-total: 40
              min-idle: 10
              timeout: 60s
              ttl: -1s
              statical: true
  mongo:
    consumer-list:
      - consumer: bsm
        store-list:
          - store: challenge
            host: ${MONGODB_HOST}
            port: ${MONGODB_PORT}
            password: ${MONGODB_PASSWORD}
            database: bsm
            addition:
              ttl: 120s
          - store: signUpLock
            host: ${MONGODB_HOST}
            port: ${MONGODB_PORT}
            password: ${MONGODB_PASSWORD}
            database: bsm
            addition:
              statical: true
          - store: signInLog
            host: ${MONGODB_HOST}
            port: ${MONGODB_PORT}
            password: ${MONGODB_PASSWORD}
            database: bsm
            addition:
              statical: true
ricciliao:
  x:
    common:
      time-zone: GMT+8
      consumer: cache-provider
      version: ${project.version}
    log:
      executor:
        enable: false